name: laravel
icon: laravel
title: Laravel

services:
- name: php
  title: PHP
  service: laravel-php
  required: true
  options:
  - version: '8.3'
    default: true
  - version: '8.2'
  - version: '8.1'
  derivatives:
  - name: sshd
    service: laravel-php-sshd
  - name: queue
    service: laravel-php-queue
  volumes:
  - name: storage
    size: 20
  links:
  - name: db
    service: mariadb
  - name: redis
    service: redis
  - name: storage
    service: storage-nfs

- name: nginx
  title: Nginx
  service: laravel-nginx
  required: true
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  required: true  
  service: mariadb
  volumes:
  - name: data
    size: 10   

- name: storage-nfs
  title: Storage NFS
  service: nfs-ganesha
  volumes:
  - name: export
    size: 25

- name: cloud-mariadb
  title: Cloud MariaDB
  service: cloud-mariadb
  disabled: true
  options:
  - version: '10.3'

- name: cloud-mysql
  title: Cloud MySQL
  service: cloud-mysql
  disabled: true
  options:
  - version: '5.7'
  - version: '8'

- name: redis
  required: false
  title: Redis
  service: redis
