name: laravel
icon: laravel
title: Laravel

services:
- name: php
  title: PHP
  service: laravel-php
  required: true
  options:
  - version: '8.3'
    default: true
  derivatives:
  - name: sshd
    service: laravel-php-sshd
  - name: queue
    service: laravel-php-queue
  volumes:
  - name: storage
    size: 20
  links:
  - name: db
    service: mariadb
  - name: redis
    service: valkey
  - name: storage
    service: files-nfs
  - name: sendmail
    service: opensmtpd

- name: nginx
  title: Nginx
  service: laravel-nginx
  required: true
  links:
  - name: backend
    service: php

- name: mariadb
  title: MariaDB
  required: true  
  service: mariadb
  volumes:
  - name: data
    size: 10   

- name: files-nfs
  title: Files NFS storage
  service: nfs-provisioner
  volumes:
  - name: data
    size: 25

- name: valkey
  required: false
  title: Valkey
  service: valkey

- name: opensmtpd
  required: false
  title: OpenSMTPD
  service: opensmtpd

- name: gotenberg
  required: false
  title: Gotenberg
  service: gotenberg

- name: cloud-mariadb
  title: Cloud MariaDB
  service: cloud-mariadb
  disabled: true
  options:
  - version: '10.3'

- name: cloud-mysql
  title: Cloud MySQL
  service: cloud-mysql
  disabled: true
  options:
  - version: '5.7'
  - version: '8'
